server.port=8078
server.address=0.0.0.0
spring.main.web-application-type=reactive
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://fibertechandia:fo82yPNOXU5GMQam@cluster0.13xuhrg.mongodb.net/fibertechia?retryWrites=true&w=majority&appName=Cluster0}
spring.data.mongodb.database=${MONGO_DB_NAME:fibertechia}
application.security.jwt.secret-key=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
external-api.support-ms.url=${SUPPORT_MS_URL:https://support.alamodaperu.online}
neuro-ia.api.url=${NEUROIA_MS_URL:https://neuroia.alamodaperu.online}
//external-api.evolution.url=${EVOLUTION_API_URL:https://evolution.alamodaperu.online}
external-api.evolution.apikey=${EVOLUTION_API_KEY:evolution-apikey-default}
external-api.evolution.url=${EVOLUTION_API_URL:http://localhost:8080}
cors.allowed-origins=${CORS_ORIGINS:http://localhost:4200,http://localhost:8078,http://spicontrol.local:4200,https://alamodaperu.online,https://spicontrol.online,https://alamoda-frontend-1068521170727.us-central1.run.app}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.codec.max-in-memory-size=100MB
application.pdf.ai-prompt-code=PDF_LAYOUT_AI_GEOMETRY_COMPILER_V2
